# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfV8B4fflSOXupAlnukP5P9aB50M_77N
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# Predefined ticker options
COMPANY_TICKERS = {
    "Google (GOOG)": "GOOG",
    "Apple (AAPL)": "AAPL",
    "Amazon (AMZN)": "AMZN",
    "Microsoft (MSFT)": "MSFT",
    "Tesla (TSLA)": "TSLA"
}

# Function to fetch stock data
def fetch_stock_data(ticker, start_date, end_date):
    stock = yf.download(ticker, start=start_date, end=end_date)
    stock['Date'] = stock.index
    return stock

# Function to predict stock prices
def predict_stock_prices(data, days_to_predict=30):
    data['Date_ordinal'] = pd.to_datetime(data['Date']).map(pd.Timestamp.toordinal)
    X = np.array(data['Date_ordinal']).reshape(-1, 1)
    y = data['Close']

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model = LinearRegression()
    model.fit(X_train, y_train)

    # Predict future prices
    future_dates = np.array(
        [data['Date_ordinal'].max() + i for i in range(1, days_to_predict + 1)]
    ).reshape(-1, 1)
    predicted_prices = model.predict(future_dates)

    return future_dates, predicted_prices

# Streamlit interface
st.set_page_config(page_title="Stock Price Tracker", layout="wide", page_icon="📈")

# Title and description
st.title("Stock Price Tracker and Predictor 📈")
st.write("Analyze historical stock data and predict future stock prices with linear regression.")

# Sidebar for user inputs
st.sidebar.header("Input Parameters")
company_name = st.sidebar.selectbox("Select a Company:", options=list(COMPANY_TICKERS.keys()))
ticker = COMPANY_TICKERS[company_name]
start_date = st.sidebar.date_input("Select the Start Date for Raw Data", datetime(2020, 1, 1))
end_date = st.sidebar.date_input("Select the End Date for Raw Data", datetime.now())
days_to_predict = st.sidebar.slider("Days to Predict", 1, 60, 30)

if st.sidebar.button("Fetch Data"):
    # Fetch data
    data = fetch_stock_data(ticker, start_date, end_date)

    if not data.empty:
        # Display stock data chart
        st.markdown(f"### Stock Data for {company_name}")
        st.line_chart(data['Close'])

        # Predict future prices
        st.markdown(f"### Predicted Prices for Next {days_to_predict} Days")
        future_dates, predicted_prices = predict_stock_prices(data, days_to_predict)
        st.line_chart(predicted_prices)

        # Display raw data
        st.markdown(f"### Raw Data Used for Predictions (From {start_date} to {end_date})")
        st.dataframe(data)
    else:
        st.error(f"No data available for {company_name} within the selected date range.")